kafka:
  bootstrap:
    servers: 192.168.1.107:9092
  topic:
    name: fin-trans
  producer:
    acks: 1
    retries: 3
    batch:
      size: 16384
    linger:
      ms: 1
    buffer:
      memory: 33554432

producer:
  transactions:
    per:
      second: 25000